### ISSUE TITLE
Get-TeamsCallQueue only returns the first 100 items

### ISSUE THREAD

**Issue by bgkilian** [DEberhardt/TeamsFunctions#94] opened 2021-08-03 16:50 UTC
Get-TeamsCallQueue only returns the first 100 items.  I know there is a limitation in the Get-CsCallQueue command, but is a workaround possible? I see there is a -skip option, but I have not been successful in modifying the script for that.

**Comment by DEberhardt** [comment] 2021-08-03 19:15
Hello,

I was looking at paging parameters, but so far, couldn't make them fit quite in yet. `-First` and `-Skip` are currently not available. Maybe one for 20.09 :)

`Get-TeamsCallQueue` was designed to improve output for individual queues, however, it should be possible to get more than hundred 😄 
For running it without a parameter, I am simply running Get-CsCallQueue and return only the DisplayName... I could use the `-All` Parameter of course, this should work. To be honest, I was not aware of this limitation

```powershell
    # Capturing no input
    if (-not $PSBoundParameters.ContainsKey('Name') -and -not $PSBoundParameters.ContainsKey('SearchString')) {
      Write-Information 'No Parameters - Listing names only. To query individual items, please provide Parameter Name or SearchString'
      Get-CsCallQueue -WarningAction SilentlyContinue -ErrorAction SilentlyContinue | Select-Object Name
      return
    }
```

you'd be after this one:
```powershell
      Get-CsCallQueue -All -WarningAction SilentlyContinue -ErrorAction SilentlyContinue | Select-Object Name
```

**Comment by DEberhardt** [comment] 2021-09-04 16:12
As I cannot get around this limitation of `Get-CsCallQueue`, I will have to close this one.

**Comment by DEberhardt** [comment] 2022-02-21 19:18
Reopening to track refactoring of `Get-TeamsCallQueue` with the following:

- [ ] Add `SupportsPaging` to enable `-First` and `-Skip` out of the box
- [ ] Rewrite PROCESS block
  - [ ] Create worker functions (in BEGIN)
  - [ ] Simplify PROCESS block to use paging when querying
- [ ] Add counters to END block
- [ ] Repeat exercise for `Get-TeamsAutoAttendant`
- [ ] Repeat also for `Get-TeamsResourceAccount`?

Slotted for v22.4, maybe even for v22.3

PS: May need to scope this out more, but don't have much time to think it through further.

**Comment by DEberhardt** [comment] 2022-02-21 21:21
Good news - I have made some progress and have reworked this in the Branch CQpaging.
Needs more testing, but otherwise it is ready for the DEV channel.

This will be in v22.3 beginning of March, hopefully I can add the same to `Get-TeamsAutoAttendant` as well.

**Comment by DEberhardt** [comment] 2022-02-21 21:25
#125

**Comment by DEberhardt** [comment] 2022-02-21 23:53
Miraculously I have managed to refactor all three CmdLets to now support paging. Horray 🛩️ 
Will test them thoroughly in the coming weeks

**Comment by DEberhardt** [comment] 2022-02-24 23:54
#128 is in - now supporting Paging for CallQueues, Auto Attendants and Resource Accounts.
It still is limited to 100 entries, but that is by design. Afaik, Get-CsCallQueue does not deliver any more...?

**Closed by DEberhardt** 2022-02-24 23:54 UTC
Labels: limitation
